# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X73_pjh18QlxJwAjevqOFlzAOfw1BB6K
"""

from pathlib import Path
import textwrap
import zipfile

root = Path("/mnt/data/SACO_CA_GitHub")
(root / "saco_ca").mkdir(parents=True, exist_ok=True)
(root / "outputs").mkdir(exist_ok=True)

files = {}

files["saco_ca/__init__.py"] = r'''"""
SACO-CA: Self-Adaptive Cheetah Optimization-Based Clustering.

Reference implementation based on the supplied SACO-CA pseudocode:
- fitness evaluation using residual energy, distance, cluster balance,
  and FSO link quality;
- searching, attacking, sit-and-wait, and leave-and-return behaviours;
- global-best preservation;
- discrete control-node (CN) repair for sensor-node indices.
"""

__version__ = "1.0.0"
'''

files["saco_ca/config.py"] = r'''from dataclasses import dataclass


@dataclass
class SACOConfig:
    # Network
    n_nodes: int = 500
    n_control_nodes: int = 40
    field_x: float = 1000.0
    field_y: float = 1000.0
    initial_energy: float = 2.0

    # Optimizer
    population_size: int = 30
    max_iterations: int = 300
    dimensions: int | None = None
    seed: int = 42

    # Fitness weights from the proposed formulation
    w1: float = 0.35  # energy
    w2: float = 0.25  # distance
    w3: float = 0.20  # cluster balance
    w4: float = 0.20  # FSO quality

    # FSO/link model
    max_fso_distance: float = 1000.0
    attenuation_coefficient: float = 0.001
    alignment_std: float = 0.03
    turbidity_std: float = 0.02

    # Cheetah-inspired search parameters
    hunting_time_scale: float = 60.0
    sit_wait_probability: float = 0.30
    attack_probability: float = 0.60
    leave_return_probability: float = 0.20
    exploration_scale: float = 0.15

    def __post_init__(self):
        if self.dimensions is None:
            self.dimensions = self.n_control_nodes

        if self.n_control_nodes > self.n_nodes:
            raise ValueError("n_control_nodes cannot exceed n_nodes.")

        if abs(self.w1 + self.w2 + self.w3 + self.w4 - 1.0) > 1e-9:
            raise ValueError("Fitness weights must sum to 1.")
'''

files["saco_ca/network.py"] = r'''from dataclasses import dataclass
import numpy as np

from .config import SACOConfig


@dataclass
class Network:
    positions: np.ndarray
    residual_energy: np.ndarray
    fso_quality: np.ndarray


def create_network(cfg: SACOConfig) -> Network:
    """
    Create a reproducible underwater optical sensor network.

    Nodes are represented by 2-D coordinates. The FSO quality matrix is
    calculated from distance, attenuation, alignment loss and turbidity
    perturbation. Values are clipped to [0, 1].
    """
    rng = np.random.default_rng(cfg.seed)

    positions = rng.uniform(
        low=[0.0, 0.0],
        high=[cfg.field_x, cfg.field_y],
        size=(cfg.n_nodes, 2),
    )

    residual_energy = np.full(cfg.n_nodes, cfg.initial_energy, dtype=float)

    # Pairwise Euclidean distance
    diff = positions[:, None, :] - positions[None, :, :]
    distances = np.linalg.norm(diff, axis=2)

    # A compact normalized FSO quality model.
    # q_ij = exp(-attenuation * d) * alignment * turbidity
    alignment = np.clip(
        1.0 - np.abs(rng.normal(0.0, cfg.alignment_std, distances.shape)),
        0.0,
        1.0,
    )
    turbidity = np.clip(
        np.exp(-np.abs(rng.normal(0.0, cfg.turbidity_std, distances.shape))),
        0.0,
        1.0,
    )

    fso_quality = (
        np.exp(-cfg.attenuation_coefficient * distances)
        * alignment
        * turbidity
    )
    np.fill_diagonal(fso_quality, 1.0)
    fso_quality = np.clip(fso_quality, 0.0, 1.0)

    return Network(
        positions=positions,
        residual_energy=residual_energy,
        fso_quality=fso_quality,
    )
'''

files["saco_ca/fitness.py"] = r'''import numpy as np

from .config import SACOConfig
from .network import Network


def decode_control_nodes(position: np.ndarray, n_nodes: int, k: int) -> np.ndarray:
    """
    Convert continuous search-agent positions into exactly k unique
    discrete sensor-node indices.

    Mapping:
      1. round continuous coordinates to node indices;
      2. clip to the feasible range;
      3. remove duplicates;
      4. fill missing nodes using unused indices.

    This makes the continuous optimizer compatible with the discrete CN
    selection problem described in the supplied pseudocode.
    """
    raw = np.rint(position).astype(int)
    raw = np.clip(raw, 0, n_nodes - 1)

    selected = []
    used = set()

    for node in raw:
        if int(node) not in used:
            selected.append(int(node))
            used.add(int(node))
        if len(selected) == k:
            break

    if len(selected) < k:
        for node in np.argsort(-np.bincount(raw, minlength=n_nodes)):
            node = int(node)
            if node not in used:
                selected.append(node)
                used.add(node)
            if len(selected) == k:
                break

    if len(selected) < k:
        for node in range(n_nodes):
            if node not in used:
                selected.append(node)
                used.add(node)
            if len(selected) == k:
                break

    return np.asarray(selected, dtype=int)


def evaluate_fitness(
    position: np.ndarray,
    network: Network,
    cfg: SACOConfig,
) -> tuple[float, dict]:
    """
    Implements Equation (2):

    F(CH_i) =
        w1 * (1 - Ei/Emax)
      + w2 * (Di/Dmax)
      + w3 * (CBi/CBmax)
      + w4 * (1 - Qi/Qmax)

    Lower fitness is better.
    """
    cn = decode_control_nodes(position, cfg.n_nodes, cfg.n_control_nodes)

    energy = network.residual_energy
    emax = max(float(np.max(energy)), 1e-12)
    energy_term = float(np.mean(1.0 - energy[cn] / emax))

    # Assign each sensor to its nearest CN.
    sensor_to_cn_dist = np.linalg.norm(
        network.positions[:, None, :] - network.positions[cn][None, :, :],
        axis=2,
    )
    nearest_cn = np.argmin(sensor_to_cn_dist, axis=1)
    min_distances = sensor_to_cn_dist[np.arange(cfg.n_nodes), nearest_cn]

    d_i = float(np.mean(min_distances))
    d_max = max(float(np.max(sensor_to_cn_dist)), 1e-12)
    distance_term = d_i / d_max

    # Cluster balance factor:
    # CB = (1/K) * sum_k (N_k - Nbar)^2
    cluster_sizes = np.bincount(
        nearest_cn,
        minlength=cfg.n_control_nodes,
    ).astype(float)
    n_bar = cfg.n_nodes / cfg.n_control_nodes
    cb_i = float(np.mean((cluster_sizes - n_bar) ** 2))

    # Maximum possible variance-like reference for normalization.
    # This is a stable implementation-level CBmax.
    cb_max = max(
        ((cfg.n_nodes - n_bar) ** 2
         + (cfg.n_control_nodes - 1) * (n_bar ** 2))
        / cfg.n_control_nodes,
        1e-12,
    )
    cluster_balance_term = min(cb_i / cb_max, 1.0)

    # Average FSO quality between each CN and its assigned sensors.
    q_values = network.fso_quality[cn[nearest_cn], np.arange(cfg.n_nodes)]
    q_i = float(np.mean(q_values))
    q_max = max(float(np.max(network.fso_quality)), 1e-12)
    fso_term = float(1.0 - q_i / q_max)

    fitness = (
        cfg.w1 * energy_term
        + cfg.w2 * distance_term
        + cfg.w3 * cluster_balance_term
        + cfg.w4 * fso_term
    )

    details = {
        "control_nodes": cn,
        "energy_term": energy_term,
        "distance_term": distance_term,
        "cluster_balance_term": cluster_balance_term,
        "fso_term": fso_term,
        "average_distance": d_i,
        "cluster_balance": cb_i,
        "average_fso_quality": q_i,
        "fitness": float(fitness),
    }

    return float(fitness), details
'''

files["saco_ca/optimizer.py"] = r'''import numpy as np

from .config import SACOConfig
from .fitness import evaluate_fitness
from .network import Network


class SACOCA:
    """
    Self-Adaptive Cheetah Optimization-Based Clustering.

    The implementation follows the supplied 40-line pseudocode at the
    algorithmic level. The original manuscript notation for SF, TR, TU,
    and the exact position-update equations is not fully specified in the
    supplied images; therefore, these update rules are implemented as
    configurable cheetah-inspired numerical operators.
    """

    def __init__(self, network: Network, cfg: SACOConfig):
        self.network = network
        self.cfg = cfg
        self.rng = np.random.default_rng(cfg.seed)

        self.lower = 0.0
        self.upper = float(cfg.n_nodes - 1)

        # Line 1: initialize positions of all search agents.
        self.positions = self.rng.uniform(
            self.lower,
            self.upper,
            size=(cfg.population_size, cfg.dimensions),
        )

        self.fitness = np.full(cfg.population_size, np.inf)
        self.details = [None] * cfg.population_size

        self.best_position = None
        self.best_fitness = np.inf
        self.best_details = None

        self.convergence = []

    def _evaluate_population(self):
        for i in range(self.cfg.population_size):
            fit, details = evaluate_fitness(
                self.positions[i], self.network, self.cfg
            )
            self.fitness[i] = fit
            self.details[i] = details

            if fit < self.best_fitness:
                self.best_fitness = fit
                self.best_position = self.positions[i].copy()
                self.best_details = details.copy()

    def _adaptive_inertia(self, iteration: int) -> float:
        # Self-adaptive inertia: larger exploration at the beginning,
        # progressively more exploitation near the final iteration.
        progress = iteration / max(self.cfg.max_iterations - 1, 1)
        return 0.90 - 0.70 * progress

    def _searching_behaviour(self, x, leader, inertia):
        r = self.rng.uniform(0.0, 1.0, size=self.cfg.dimensions)
        exploration = (
            self.cfg.exploration_scale
            * (1.0 - r)
            * (self.upper - self.lower)
        )
        return (
            x
            + inertia * r * (leader - x)
            + self.rng.normal(0.0, 1.0, x.shape) * exploration
        )

    def _attacking_behaviour(self, x, leader, prey, iteration):
        # Exploitation around leader/prey.
        sf = self.rng.uniform(0.0, 1.0)
        tr = self.rng.uniform(0.0, 1.0)
        tu = self.rng.uniform(0.0, 1.0)

        direction = (
            sf * (leader - x)
            + tr * (prey - x)
            + tu * (leader - prey)
        )
        step = np.exp(-2.0 * iteration / max(self.cfg.max_iterations, 1))
        return x + step * direction + self.rng.normal(0, 0.05, x.shape)

    def _sit_and_wait_behaviour(self, x, leader):
        # Small local perturbation while remaining close to the leader.
        noise = self.rng.normal(
            0.0,
            self.cfg.exploration_scale * (self.upper - self.lower) * 0.05,
            size=x.shape,
        )
        return x + 0.25 * (leader - x) + noise

    def _leave_and_return(self, previous_position):
        # Preserve leader position in the event of a hunting-time trigger,
        # then restart exploration around a randomly generated position.
        new_position = self.rng.uniform(
            self.lower,
            self.upper,
            size=self.cfg.dimensions,
        )
        return new_position, previous_position.copy()

    def run(self):
        cfg = self.cfg

        # Lines 2-4: initial fitness, leader, prey/home positions.
        self._evaluate_population()
        leader = self.best_position.copy()
        prey = leader.copy()
        home = self.rng.uniform(
            self.lower,
            self.upper,
            size=cfg.dimensions,
        )

        tm = 0

        # Line 6: T = 60 * ceil(Dm/10)
        hunting_time = cfg.hunting_time_scale * np.ceil(cfg.dimensions / 10)

        # Lines 7-36: main optimization loop.
        for iteration in range(cfg.max_iterations):
            inertia = self._adaptive_inertia(iteration)

            # Lines 8-10: random ordering/agent preservation.
            order = np.argsort(self.fitness)
            self.positions = self.positions[order]
            self.fitness = self.fitness[order]
            self.details = [self.details[i] for i in order]

            # Line 9: random search agent.
            random_idx = self.rng.integers(0, cfg.population_size)

            old_leader = leader.copy()

            for i in range(cfg.population_size):
                x = self.positions[i].copy()

                # Random variables RN1, RN2, RN3.
                rn1, rn2, rn3 = self.rng.uniform(0.0, 1.0, 3)

                # Select a prey candidate different from current agent.
                prey_idx = self.rng.integers(0, cfg.population_size)
                prey_candidate = self.positions[prey_idx].copy()

                # Searching vs attacking decision.
                if rn2 < rn3:
                    rn4 = self.rng.normal(0.0, 3.0)

                    # SF >= N4 -> searching; otherwise attacking.
                    if rn1 >= rn4:
                        new_x = self._searching_behaviour(
                            x, leader, inertia
                        )
                    else:
                        new_x = self._attacking_behaviour(
                            x, leader, prey_candidate, iteration
                        )
                else:
                    new_x = self._sit_and_wait_behaviour(x, leader)

                # Occasional sit-and-wait / home influence.
                if self.rng.random() < cfg.sit_wait_probability * 0.10:
                    new_x = 0.8 * new_x + 0.2 * home

                self.positions[i] = np.clip(
                    new_x, self.lower, self.upper
                )

            # Lines 25-27: update fitness and leader.
            self._evaluate_population()

            if self.best_fitness < np.inf:
                leader = self.best_position.copy()

            # Lines 28-33: hunting time and leave-and-return behaviour.
            tm += 1
            if tm > self.rng.uniform(0.0, 1.0) * hunting_time:
                # Preserve leader position.
                preserved_leader = leader.copy()

                # Restart a subset of poorer agents.
                n_restart = max(1, cfg.population_size // 10)
                worst = np.argsort(self.fitness)[-n_restart:]

                for idx in worst:
                    self.positions[idx], _ = self._leave_and_return(
                        preserved_leader
                    )

                tm = 0
                self._evaluate_population()
                leader = self.best_position.copy()

            # Lines 34-35: iteration update and global-best leader.
            self.convergence.append(self.best_fitness)

            # Keep an explicit global-best agent in the population.
            worst_idx = int(np.argmax(self.fitness))
            if self.best_position is not None:
                self.positions[worst_idx] = self.best_position.copy()
                self.fitness[worst_idx] = self.best_fitness
                self.details[worst_idx] = self.best_details.copy()

            # Keep variables referenced by the supplied pseudocode.
            _ = random_idx, old_leader

        # Lines 37-40: return global-best solution as optimized CNs.
        optimized_cns = np.sort(
            self.best_details["control_nodes"]
        )

        return {
            "control_nodes": optimized_cns,
            "fitness": self.best_fitness,
            "details": self.best_details,
            "convergence": np.asarray(self.convergence),
            "best_position": self.best_position,
        }
'''

files["run_saco_ca.py"] = r'''import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from saco_ca.config import SACOConfig
from saco_ca.network import create_network
from saco_ca.optimizer import SACOCA


def main():
    parser = argparse.ArgumentParser(
        description="Run the SACO-CA Self-Adaptive Cheetah Optimization-Based Clustering algorithm."
    )
    parser.add_argument("--nodes", type=int, default=500)
    parser.add_argument("--cn", type=int, default=40)
    parser.add_argument("--population", type=int, default=30)
    parser.add_argument("--iterations", type=int, default=300)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--output", type=str, default="outputs")
    args = parser.parse_args()

    output = Path(args.output)
    output.mkdir(parents=True, exist_ok=True)

    cfg = SACOConfig(
        n_nodes=args.nodes,
        n_control_nodes=args.cn,
        population_size=args.population,
        max_iterations=args.iterations,
        seed=args.seed,
    )

    network = create_network(cfg)
    optimizer = SACOCA(network, cfg)
    result = optimizer.run()

    # Save optimized CNs.
    cn_df = pd.DataFrame({
        "control_node": result["control_nodes"] + 1,  # 1-based manuscript indexing
    })
    cn_df.to_csv(output / "optimized_control_nodes.csv", index=False)

    # Save fitness components.
    summary = pd.DataFrame([{
        "fitness": result["fitness"],
        "energy_term": result["details"]["energy_term"],
        "distance_term": result["details"]["distance_term"],
        "cluster_balance_term": result["details"]["cluster_balance_term"],
        "fso_term": result["details"]["fso_term"],
        "average_distance": result["details"]["average_distance"],
        "cluster_balance": result["details"]["cluster_balance"],
        "average_fso_quality": result["details"]["average_fso_quality"],
    }])
    summary.to_csv(output / "fitness_summary.csv", index=False)

    # Save convergence.
    convergence_df = pd.DataFrame({
        "iteration": np.arange(1, len(result["convergence"]) + 1),
        "best_fitness": result["convergence"],
    })
    convergence_df.to_csv(output / "convergence.csv", index=False)

    # Publication-friendly convergence figure.
    plt.figure(figsize=(8, 5))
    plt.plot(
        convergence_df["iteration"],
        convergence_df["best_fitness"],
        linewidth=2,
    )
    plt.xlabel("Iteration")
    plt.ylabel("Global Best Fitness")
    plt.title("SACO-CA Convergence")
    plt.grid(True, alpha=0.25)
    plt.tight_layout()
    plt.savefig(output / "saco_ca_convergence.png", dpi=300)
    plt.close()

    print("\nSACO-CA completed")
    print("-" * 50)
    print(f"Nodes                : {cfg.n_nodes}")
    print(f"Control Nodes (K)    : {cfg.n_control_nodes}")
    print(f"Population Size      : {cfg.population_size}")
    print(f"Iterations           : {cfg.max_iterations}")
    print(f"Seed                 : {cfg.seed}")
    print(f"Best Fitness         : {result['fitness']:.8f}")
    print(
        "Optimized CNs (1-based): "
        + ", ".join(map(str, result["control_nodes"] + 1))
    )
    print(f"Results saved to     : {output.resolve()}")


if __name__ == "__main__":
    main()
'''

files["requirements.txt"] = r'''numpy>=1.24
pandas>=2.0
matplotlib>=3.7
'''

files["README.md"] = r'''# SACO-CA: Self-Adaptive Cheetah Optimization-Based Clustering

This repository contains a Python reference implementation of the **Self-Adaptive Cheetah Optimization-Based Clustering Algorithm (SACO-CA)** based on the supplied manuscript pseudocode.

## What is implemented?

The implementation covers:

1. Initialization of search-agent positions.
2. Fitness evaluation using the proposed Equation (2).
3. Global-best/leader selection.
4. Prey and population-home initialization.
5. Hunting-time calculation.
6. Searching behaviour.
7. Attacking behaviour.
8. Sit-and-wait behaviour.
9. Leave-and-return behaviour.
10. Adaptive inertia.
11. Global-best preservation.
12. Continuous-to-discrete mapping for Control Node (CN) selection.
13. Duplicate removal and feasibility repair.
14. Convergence recording.
15. Export of optimized CNs and fitness results.

## Fitness function

The implemented fitness function is:

F(CH_i) =
w1(1 - E_i/E_max)
+ w2(D_i/D_max)
+ w3(CB_i/CB_max)
+ w4(1 - Q_i/Q_max)

The default manuscript weights are:

- w1 = 0.35: residual energy
- w2 = 0.25: communication distance
- w3 = 0.20: cluster balance
- w4 = 0.20: FSO link quality

Lower fitness is better.

## Discrete Control Node mapping

The optimizer internally uses continuous search-agent positions, while the actual solution must contain valid sensor-node IDs.

The implementation therefore:

- rounds continuous positions to node indices;
- clips indices to the valid range;
- removes duplicate node IDs;
- fills missing positions with unused feasible nodes;
- returns exactly K Control Nodes.

This makes the implementation reproducible for the discrete CN-selection problem.

## Project structure

```text
SACO_CA_GitHub/
├── README.md
├── requirements.txt
├── run_saco_ca.py
├── saco_ca/
│   ├── __init__.py
│   ├── config.py
│   ├── network.py
│   ├── fitness.py
│   └── optimizer.py
└── outputs/
```
'''